language: go
sudo: required

go:
  - 1.x

services:
  - docker

script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t $DOCKER_USERNAME/wechat-enterprise .
  - docker push $DOCKER_USERNAME/wechat-enterprise
  - docker images
